server:
  port: 12021

spring:
  application:
    version: 1.0.1
    description: dev环境

axinger:
  user:
    username: jim
    password: 1234
    range: # 必须缩进两格
      min: 1 # 必须缩进四格
      max: 100

  person:
    id: 1
    name: jim
    age: 18
    time: 12:00:00
    time2: "13:00:00"
    created-date: "2000-01-01 13:00:00"
    created-time: "13:00:01"
    updated-date-time: "2000-01-02 14:00:00"
    updated-date: "2000-01-02"
    updated-time: "14:00:01"
  doc:
    title: mvc测试

show:
  # 湿度
  humidity:
    min: 40.0
    max: 65.0
  # 温度
  temperature:
    min: 150
    max: 300



