server:
  port: 12022

spring:
  application:
    version: 2.0.1
    description: prd环境

axinger:
  user:
    username: jim
    password: 1234
  person:
    id: 1

show:
  # 湿度
  humidity:
    min: 40.0
    max: 65.0
  # 温度
  temperature:
    min: 150
    max: 300



